title: Example blog
description: ""
header_text: ""
footer_text: Copyright 2020 Adam Blades
header_feature_image: /uploads/pages.jpg
logo: ../uploads/books4screen.jpg
favicon: /uploads/favicon.ico
gridlayout: false
upzoom: true
