title: Example blog
description: ""
header_text: ""
footer_text: Copyright 2020 Adam Blades
header_feature_image: /uploads/pages.jpg
bannerheight: "10"
logo: ../uploads/867FAB82-62D7-4C53-8EDC-5114095CF8AA.jpeg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
